import type { PersonaId } from "@/lib/types";

/**
 * Desk-fit scale — seated hips ≈ chair top (~0.38).
 * Feet are re-clamped to the floor at runtime in RpmAvatar.
 */
export const AVATAR_SCALE = 0.72;

export type AvatarClipName =
  | "SitIdle"
  | "Typing"
  | "Walk"
  | "Greet"
  | "StandIdle";

export type AvatarDef = {
  url: string;
  gender: "male" | "female";
};

/** Local RPM-style GLBs generated by scripts/generate-avatars.mjs */
export const AVATAR_BY_PERSONA: Record<PersonaId, AvatarDef> = {
  rajesh: { url: "/avatars/rajesh.glb", gender: "male" },
  karthik: { url: "/avatars/karthik.glb", gender: "male" },
  lavanya: { url: "/avatars/lavanya.glb", gender: "female" },
  aravind: { url: "/avatars/aravind.glb", gender: "male" },
  meenakshi: { url: "/avatars/meenakshi.glb", gender: "female" },
  muthu: { url: "/avatars/muthu.glb", gender: "male" },
  kabilan: { url: "/avatars/kabilan.glb", gender: "male" },
  helpdesk: { url: "/avatars/helpdesk.glb", gender: "female" },
};

/** Controllable logged-in visitor on the office floor. */
export const PLAYER_AVATAR: AvatarDef = {
  url: "/avatars/player.glb",
  gender: "male",
};

export const ALL_AVATAR_URLS = [
  ...Object.values(AVATAR_BY_PERSONA).map((a) => a.url),
  PLAYER_AVATAR.url,
];

/** How close the player must be to trigger an agent greeting. */
export const PLAYER_GREET_RADIUS = 1.45;
