import type { PersonaId } from "@/lib/types";

/** Desk-proportioned scale — seated hips land on chair (~0.38). */
export const AVATAR_SCALE = 0.78;

export type AvatarClipName =
  | "SitIdle"
  | "Typing"
  | "Walk"
  | "Greet"
  | "StandIdle";

export type AvatarDef = {
  url: string;
  gender: "male" | "female";
};

/** Local RPM-style GLBs generated by scripts/generate-avatars.mjs */
export const AVATAR_BY_PERSONA: Record<PersonaId, AvatarDef> = {
  rajesh: { url: "/avatars/rajesh.glb", gender: "male" },
  karthik: { url: "/avatars/karthik.glb", gender: "male" },
  lavanya: { url: "/avatars/lavanya.glb", gender: "female" },
  aravind: { url: "/avatars/aravind.glb", gender: "male" },
  meenakshi: { url: "/avatars/meenakshi.glb", gender: "female" },
  muthu: { url: "/avatars/muthu.glb", gender: "male" },
  kabilan: { url: "/avatars/kabilan.glb", gender: "male" },
};

export const ALL_AVATAR_URLS = Object.values(AVATAR_BY_PERSONA).map((a) => a.url);
